---
# tasks file for ansible-docker
- name: Install docker repo
  copy: src=etc/apt/sources.list.d/docker.list dest=/etc/apt/sources.list.d/docker.list

- name: Add docker repo key
  shell: curl -sSL https://get.docker.com/gpg | sudo apt-key add -
- name: Install docker
  apt: pkg=docker-engine state=latest

- name: Start docker
  service: name=docker state=started enabled=yes
